// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB2WvacD0GPvSJ593lc2_bEJM1X1Wvfbs',
    appId: '1:308082095505:web:74138468ca97d81e891630',
    messagingSenderId: '308082095505',
    projectId: 'sketchmind-543f0',
    authDomain: 'sketchmind-543f0.firebaseapp.com',
    storageBucket: 'sketchmind-543f0.firebasestorage.app',
    measurementId: 'G-DL840ZM1XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZl3fBSCr6QUAgQo6WJ77rnVvdecd3neY',
    appId: '1:308082095505:android:51b22baf6b6fc111891630',
    messagingSenderId: '308082095505',
    projectId: 'sketchmind-543f0',
    storageBucket: 'sketchmind-543f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6A8qTsPR_MLXnVuoUCiPX6mQKyK66kco',
    appId: '1:308082095505:ios:86b1ad2d5b380d76891630',
    messagingSenderId: '308082095505',
    projectId: 'sketchmind-543f0',
    storageBucket: 'sketchmind-543f0.firebasestorage.app',
    iosBundleId: 'com.example.sketchmind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6A8qTsPR_MLXnVuoUCiPX6mQKyK66kco',
    appId: '1:308082095505:ios:86b1ad2d5b380d76891630',
    messagingSenderId: '308082095505',
    projectId: 'sketchmind-543f0',
    storageBucket: 'sketchmind-543f0.firebasestorage.app',
    iosBundleId: 'com.example.sketchmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB2WvacD0GPvSJ593lc2_bEJM1X1Wvfbs',
    appId: '1:308082095505:web:53956024fdb09f77891630',
    messagingSenderId: '308082095505',
    projectId: 'sketchmind-543f0',
    authDomain: 'sketchmind-543f0.firebaseapp.com',
    storageBucket: 'sketchmind-543f0.firebasestorage.app',
    measurementId: 'G-BNJ9MHP097',
  );
}
